import type { TypeMetadata } from "@andesine/sdk";
import type { TypesConfig } from "../config/schema";
import { compare, hash, json, literal, names, tuple, union } from "./source";
import { fragmentTypes, schemaFields } from "./schema";
import { hierarchy, treeTypes } from "./tree";

interface TypeGenerationOptions {
  /** Requested source. Omit to follow the metadata's channel or current source. */
  source?: TypesConfig["source"];
  /** Requested collection selectors, recorded as provenance. Metadata is already scoped. */
  collections?: string[];
  /** Emit exact ID bindings and per-collection entry ID unions. Defaults to false. */
  includeEntryIDs?: boolean;
  /** Emit exact path bindings and per-collection entry path unions. Defaults to false. */
  includeEntryPaths?: boolean;
  /** Emit ordered trees, including their entry identities. Defaults to false. */
  includeTree?: boolean;
}

const GENERATED_TYPES_MARKER = "// Generated by Andesine. Do not edit.";

/**
 * Convert public type metadata into deterministic, type-only TypeScript source.
 *
 * @param metadata - One complete current or published metadata response.
 * @param options - Source provenance and optional entry/tree exports. These do not filter
 * metadata; request the selected collections and optional metadata before calling this function.
 * @returns Source text with Workspace, collection, and revision types. No files are written.
 * @throws Error for unsupported metadata, inconsistent references, or missing requested extras.
 * No network, credentials, project config loading, or executable remote input is involved.
 */
const generateTypes = (metadata: TypeMetadata, options: TypeGenerationOptions = {}): string => {
  const includeEntries = Boolean(options.includeEntryIDs || options.includeEntryPaths);
  const requestedSource =
    options.source ??
    (metadata.source.kind === "published"
      ? { kind: "published", channel: metadata.source.channel }
      : { kind: "current" });
  const source: TypesConfig["source"] =
    requestedSource.kind === "current"
      ? { kind: "current" }
      : "snapshotID" in requestedSource
        ? { kind: "published", snapshotID: requestedSource.snapshotID }
        : { kind: "published", channel: requestedSource.channel };
  const sourceMismatch =
    source.kind !== metadata.source.kind ||
    (source.kind === "published" &&
      metadata.source.kind === "published" &&
      (("channel" in source && source.channel !== metadata.source.channel) ||
        ("snapshotID" in source && source.snapshotID !== metadata.source.snapshotID)));

  if (metadata.formatVersion !== 1) throw new Error("Unsupported type metadata format version.");
  if (sourceMismatch) throw new Error("Type metadata does not match the requested source.");

  if ((includeEntries || options.includeTree) && !metadata.entries) {
    throw new Error("Request entry metadata before generating entry or tree types.");
  }

  if (options.includeTree && !metadata.tree) {
    throw new Error("Request tree metadata before generating tree types.");
  }

  const collections = [...metadata.collections].sort((a, b) => compare(a.id ?? "", b.id ?? ""));
  const selected = { ...metadata, collections };
  const { descendants } = hierarchy(selected);
  const collectionNames = names(
    collections.map((row) => ({ key: row.id ?? "/", label: row.name || "Root" })),
    "Collection"
  );
  const revisions = new Map(metadata.revisions.map((revision) => [revision.revisionID, revision]));
  const usedRevisions = new Set(
    collections.flatMap((row) => row.schemaRevisionIDs).filter((id) => id !== null)
  );
  const entries =
    includeEntries || options.includeTree
      ? [...metadata.entries!].sort((a, b) => compare(a.id, b.id))
      : [];
  const collectionBindings = new Map<string, string>();
  const entryBindings = new Map<string, string>();
  const shapes = new Map<string, string>();
  const interfaces: string[] = [];
  const types: string[] = [];
  const schemaBindings: string[] = [];
  const treeBindings: string[] = [];
  const base = metadata.source.kind === "published" ? "SDK.PublishedEntryContent" : "SDK.Entry";
  const contentBase = `Omit<${base}, "schema" | "properties" | "fragments">`;
  const bind = (map: Map<string, string>, key: string, value: string) => {
    if (map.has(key)) throw new Error(`Duplicate metadata selector ${literal(key)}.`);

    map.set(key, value);
  };

  for (const collection of collections) {
    const name = collectionNames.get(collection.id ?? "/")!;

    bind(collectionBindings, collection.path, name);

    if (collection.id !== null) bind(collectionBindings, collection.id, name);
  }

  for (const entry of entries) {
    const collection = collectionBindings.get(entry.collectionID ?? "/");

    if (!collection) throw new Error(`Missing collection for entry ${literal(entry.id)}.`);
    if (entry.schemaRevisionID !== null) usedRevisions.add(entry.schemaRevisionID);

    const binding = `{ collection: ${literal(entry.collectionID ?? "/")}; schemaRevisionID: ${literal(entry.schemaRevisionID)} }`;

    if (options.includeEntryIDs) bind(entryBindings, entry.id, binding);
    if (options.includeEntryPaths) bind(entryBindings, entry.path, binding);
  }

  const revisionNames = names(
    [...usedRevisions].map((id) => ({ key: id, label: `Revision_${id}` })),
    "Schema"
  );

  for (const id of [...usedRevisions].sort(compare)) {
    const revision = revisions.get(id);

    if (!revision) throw new Error(`Missing schema revision ${literal(id)}.`);

    const fields = schemaFields(revision);
    const shapeName = `SchemaFields_${hash(fields)}`;
    const revisionName = revisionNames.get(id)!;

    shapes.set(shapeName, fields);
    interfaces.push(`export interface ${revisionName} extends ${shapeName} {
  hash: ${literal(revision.hash)};
}`);
    types.push(
      `export type ${revisionName}Content = ${contentBase} & SDK.SchemaContent<Workspace, ${literal(id)}>;`
    );
    schemaBindings.push(`    ${literal(id)}: ${revisionName};`);
  }

  for (const collection of collections) {
    const name = collectionNames.get(collection.id ?? "/")!;
    const ids = [...new Set(collection.schemaRevisionIDs)].sort((a, b) =>
      compare(a ?? "", b ?? "")
    );
    const childIDs = [...descendants.get(collection.id)!].sort(compare);
    const identity =
      metadata.source.kind === "published" ? ` & { collectionID: ${literal(collection.id)} }` : "";

    interfaces.push(`export interface ${name} extends SDK.WorkspaceCollection {
  id: ${literal(collection.id)};
  path: ${literal(collection.path)};
  schemaRevisionIDs: readonly ${tuple(ids.map(literal))};
  descendants: readonly ${tuple(childIDs.map(literal))};
}`);
    types.push(
      `export type ${name}Content = ${contentBase} & SDK.SchemaContent<Workspace, ${union(ids.map(literal))}>${identity};`
    );
    types.push(`export type ${name}StructuredContent = SDK.StructuredContent<${name}Content>;`);

    const collectionEntries = entries.filter((entry) => entry.collectionID === collection.id);

    if (options.includeEntryIDs) {
      types.push(
        `export type ${name}EntryID = ${union(collectionEntries.map((entry) => literal(entry.id)))};`
      );
    }

    if (options.includeEntryPaths) {
      types.push(
        `export type ${name}EntryPath = ${union(collectionEntries.map((entry) => literal(entry.path)))};`
      );
    }

    if (options.includeTree) {
      treeBindings.push(`    ${literal(collection.path)}: ${name}Tree;`);
      if (collection.id !== null) treeBindings.push(`    ${literal(collection.id)}: ${name}Tree;`);
    }
  }

  if (options.includeTree) {
    interfaces.push(...treeTypes(selected, collectionNames));
    types.push(`export type WorkspaceTree = {\n${treeBindings.join("\n")}\n};`);
  }

  const mapFields = [
    `  workspaceID: ${literal(metadata.workspaceID)};`,
    `  source: ${
      source.kind === "current"
        ? '{ kind: "current" }'
        : `{
    kind: "published";
    ${"snapshotID" in source ? `snapshotID: ${literal(source.snapshotID)};` : `channel: ${literal(source.channel)};`}
  }`
    };`,
    `  collections: {\n${[...collectionBindings]
      .sort(([a], [b]) => compare(a, b))
      .map(([key, value]) => `    ${literal(key)}: ${value};`)
      .join("\n")}\n  };`,
    `  schemas: {\n${schemaBindings.join("\n")}\n  };`
  ];

  if (includeEntries) {
    mapFields.push(
      `  entries: {\n${[...entryBindings]
        .sort(([a], [b]) => compare(a, b))
        .map(([key, value]) => `    ${literal(key)}: ${value};`)
        .join("\n")}\n  };`
    );
  }

  if (options.includeTree && metadata.source.kind === "published") {
    mapFields.push("  tree: WorkspaceTree;");
  }

  return [
    [
      GENERATED_TYPES_MARKER,
      `// Workspace: ${literal(metadata.workspaceID)}; source: ${json(source)}.`,
      `// Collections: ${json([...new Set(options.collections ?? [])].sort(compare))}; entry IDs: ${Boolean(options.includeEntryIDs)}; entry paths: ${Boolean(options.includeEntryPaths)}; tree: ${Boolean(options.includeTree)}.`,
      "// Types only. Configure the runtime client for the same workspace and source."
    ].join("\n"),
    'import type * as SDK from "@andesine/sdk";',
    `export interface Workspace extends SDK.WorkspaceTypeMap {\n${mapFields.join("\n")}\n}`,
    ...[...shapes]
      .sort(([a], [b]) => compare(a, b))
      .map(([name, fields]) => `interface ${name} {\n${fields}\n}`),
    ...interfaces,
    ...([...shapes.values()].some((fields) => fields.includes("FragmentDocument<"))
      ? [fragmentTypes]
      : []),
    ...types,
    ""
  ].join("\n\n");
};

export { generateTypes, GENERATED_TYPES_MARKER };
export type { TypeGenerationOptions };
