const API_VERSION = "1.0.0";
const DEFAULT_PAGE_SIZE = 50;
const MAX_PAGE_SIZE = 100;
const MAX_BULK_ITEMS = 100;
const MAX_SEARCH_RESULTS = 50;

export { API_VERSION, DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE, MAX_BULK_ITEMS, MAX_SEARCH_RESULTS };
